service: serverless-esi

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    -
      Effect: "Allow"
      Action:
        - 's3:ListBucket'
      Resource: arn:aws:s3:::test-esi-bucket
    -
      Effect: "Allow"
      Action:
        - 's3:GetObject'
      Resource: arn:aws:s3:::test-esi-bucket/*

functions:
  esi:
    handler: handler.esi
    events:
      - http:
          method: GET
          path: pages/{path+}
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')

resources:
  Resources:
    TestESIBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: test-esi-bucket
